#配置启动端口
server:
  port: 8080

  #设置热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false #页面不加载缓存，修改即时生效

#日志配置
logging:
  level:
    com.lz: debug
    org.springfromework: debug
  #file: app.log

